### ISSUE TITLE
larch server appears to be broken

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#123]
This happens with the current head of xraylarch on my machine:

```
bruce@titanium [xraylarch](master) > larch_server start
bruce@titanium [xraylarch](master) > Traceback (most recent call last):
  File "/usr/local/bin/larch", line 95, in <module>
    s.initialize_larch()
  File "/usr/local/lib/python2.7/dist-packages/larch/xmlrpc_server.py", line 128, in initialize_larch
    self.wx_evtloop = inputhook.EventLoopRunner(parent=self.wxapp)
TypeError: __init__() got an unexpected keyword argument 'parent'
```

I'm afraid the traceback points at a bit of code I don't understand, so I don't have a fix to suggest.

B

**Comment by newville** [comment]
Yikes.   I made some changes around there.  Will investigate.

**Comment by newville** [comment]
should be fixed with 47f9228743712cb537f8bcf2fc9ebe2eefe8f42c

**Comment by bruceravel** [comment]
Works!  Thanks!

**Comment by newville** [comment]
Whew!
