### ISSUE TITLE
[xas_viewer] bug in single scan specfile reader missing ydat attribute

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#286]
@newville I cannot read [ABCF002.DAT](https://github.com/xraypy/xraylarch/files/5696952/ABCF002.zip) anymore. Below the error the trace. It should be related to one of your last changes, but I cannot easily identify from where it comes. Please, could you have a look and push your changes in #285 ?

```
Cannot plot group  abcf00001
Traceback (most recent call last):
  File "/users/blissadm/local/xraylarch/larch/wxlib/columnframe.py", line 701, in onOK
    self.read_ok_cb(script, self.path, groupname=groupname,
  File "/users/blissadm/local/xraylarch/larch/wxxas/xasgui.py", line 1056, in onRead_OK
    self.install_group(groupname, filename, overwrite=overwrite)
  File "/users/blissadm/local/xraylarch/larch/wxxas/xasgui.py", line 1121, in install_group
    self.ShowFile(groupname=groupname, process=process, plot=plot)
  File "/users/blissadm/local/xraylarch/larch/wxxas/xasgui.py", line 541, in ShowFile
    cur_panel.plot(dgroup=dgroup)
  File "/users/blissadm/local/xraylarch/larch/wxxas/xasnorm_panel.py", line 864, in plot
    self.get_plot_arrays(dgroup)
  File "/users/blissadm/local/xraylarch/larch/wxxas/xasnorm_panel.py", line 756, in get_plot_arrays
    dgroup.dmude = np.gradient(dgroup.ydat)/np.gradient(dgroup.xdat)
AttributeError: 'Group' object has no attribute 'ydat'
```

**Comment by newville** [comment]
@maurov Sorry for the trouble.  I think I *had* that  "Starts with #S" file reading as a Specfile correctly and then reverted back to "use column file importer" and botched something there.....

**Comment by maurov** [comment]
Fixed in https://github.com/xraypy/xraylarch/commit/2cc6cdec607c68ee686d471e1dad0c7d40266b6a
Thanks @newville !
