### ISSUE TITLE
[xas_viewer] save project does not write new groups to disk

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#347]
@newville I have noticed a bug in xas_viewer at the "Save Project" action:

1. open xas_viewer
2. import some data
3. save project
4. make a merged group
5. save project
6. open another instance of xas_viewer
7. open the saved project
8. **all data are there except the merged groups**

If at step 5 I do "Save Project As" the data are there.

No hurry, I can look into this by myself, I open the issue just for tracking/memo purposes.

**Comment by newville** [comment]
@maurov  Oh, that's not good... will investigate.  (and agree on this as a 0.9.59 milestone, and maybe aim for end of month or so)

**Comment by maurov** [comment]
@newville I had a look into this and the problem comes when doing autobk on reading an Athena project:

[Cr_PEEK.zip](https://github.com/xraypy/xraylarch/files/8177049/Cr_PEEK.zip)

```
from larch.interpreter import Interpreter
from larch.io.athena_project import AthenaProject
_larch = Interpreter()
apj = AthenaProject(filename="Cr_PEEK.prj", _larch=_larch)
```
I get the following error from lmfit (version 1.0.3):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/esrf/rovezzi/devel/xraylarch/larch/io/athena_project.py", line 630, in __init__
    self.read(filename)
  File "/home/esrf/rovezzi/devel/xraylarch/larch/io/athena_project.py", line 819, in read
    autobk(this, _larch=self._larch, e0=float(pars.e0),
  File "/home/esrf/rovezzi/devel/xraylarch/larch/larchlib.py", line 551, in wrapper
    result = fcn(*args, **kwargs)
  File "/home/esrf/rovezzi/devel/xraylarch/larch/xafs/autobk.py", line 229, in autobk
    covar  = result.covar / redchi
AttributeError: 'MinimizerResult' object has no attribute 'covar'
```
Do you have any idea how to fix it?

**Comment by newville** [comment]
@maurov  - that works without `_larch=_larch` (which will just not try to do any processing), and it also works with XAS_Viewer (which will also read without processing, the do processing later).  
That should be easy to check for and avoid.  I'll investigate.

**Comment by newville** [comment]
@maurov Oh, yes, I see the same problem you do, so I can debug -- the error is definitely in autobk and would cause problems there anyway. 

And, I also agree that doing the autobk/fft processing should be off by default.  I think we're drifting slowly away from "reproduce Athena behavior" to "be compatible with Athena Project files".    

PS: still working toward "select point on graph *after* clicking on pin icon". And also saw a problem (and am working on a solution!) to something similar (and maybe exactly the same) as #352.

**Comment by maurov** [comment]
> @maurov Oh, yes, I see the same problem you do, so I can debug -- the error is definitely in autobk and would cause problems there anyway.

OK, thanks for looking into it.
 
> And, I also agree that doing the autobk/fft processing should be off by default. I think we're drifting slowly away from "reproduce Athena behavior" to "be compatible with Athena Project files".

Yes, I think that the default behaviour should to correctly import all the parameters and already calculated arrays stored in the Athena project file and let the GUI or the user to reprocess them on demand only. By re-running autobk/fft on read we may change what was stored in the file, and to my opinion is not what is expected by a "read" command.

> PS: still working toward "select point on graph _after_ clicking on pin icon". And also saw a problem (and am working on a solution!) to something similar (and maybe exactly the same) as #352.

OK, great! I took the initiative to tag these two issues for the 0.9.59 milestone.

**Comment by maurov** [comment]
This seems to work in 0.9.60
