### ISSUE TITLE
Handle broken external HDF5 links

### ISSUE THREAD

**Issue by woutdenolf** [xraypy/xraylarch#354]
Opening an HDF5 file with broken external links gives this error:

```
Traceback (most recent call last):
  File "/mnt/multipath-shares/sware/exp/packages/ubuntu20.04/x86_64/spectroscopy/2022.02.15/lib/python3.9/site-packages/larch/wxxas/xasgui.py", line 799, in onReadDialog
    self.onRead(path)
  File "/mnt/multipath-shares/sware/exp/packages/ubuntu20.04/x86_64/spectroscopy/2022.02.15/lib/python3.9/site-packages/larch/wxxas/xasgui.py", line 822, in onRead
    self.show_subframe('readfile', ColumnDataFileFrame,
  File "/mnt/multipath-shares/sware/exp/packages/ubuntu20.04/x86_64/spectroscopy/2022.02.15/lib/python3.9/site-packages/larch/wxxas/xasgui.py", line 754, in show_subframe
    self.subframes[name] = frameclass(self, **opts)
  File "/mnt/multipath-shares/sware/exp/packages/ubuntu20.04/x86_64/spectroscopy/2022.02.15/lib/python3.9/site-packages/larch/wxlib/columnframe.py", line 331, in __init__
    group = self.initgroup = self.read_column_file(self.path)
  File "/mnt/multipath-shares/sware/exp/packages/ubuntu20.04/x86_64/spectroscopy/2022.02.15/lib/python3.9/site-packages/larch/wxlib/columnframe.py", line 607, in read_column_file
    text = fh.read().decode('utf-8').replace('\r\n', '\n').replace('\r', '\n')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by woutdenolf** [comment]
To check whether a file is an HDF5 file:

```python
def is_hdf5(filename):
    with open(filename,"rb") as f:
        return f.read(8) == b'\x89HDF\r\n\x1a\n'
```

**Comment by woutdenolf** [comment]
This is the problem:

```python
def is_specfile(filename):
    """tests whether file may be a Specfile (text or HDF5)"""
    if not os.path.exists(filename):
        return False
    with open(filename, "rb") as fh:
        topbytes = fh.read(10)
    scans = None
    if (
        topbytes.startswith(b"\x89HDF\r")  # HDF5
        or topbytes.startswith(b"#S ")  # partial Spec file (1 scan)
        or topbytes.startswith(b"#F ")  # full Spec file
    ):  # full specscan
        try:
            scans = DataSourceSpecH5(filename)._scans
        except Exception:
            pass
    return scans is not None
```

`DataSourceSpecH5(filename)._scans` fails due to the broken link and as a result larch thinks this is not a spec file and tries to read it as an ascii file which gives the decode error.

**Comment by newville** [comment]
@woutdenolf thanks... I wonder if silx has a recommended way to open spec/hdf5 files that is tolerant of missing external links.  
In fact, can you open that file with silx?

**Comment by woutdenolf** [comment]
Yes I can

![image](https://user-images.githubusercontent.com/7264703/156425786-9999d283-50e2-493e-a294-c3885163e0fb.png)

**Comment by woutdenolf** [comment]
I made a fix which handles this in `larch.io.specfile_reader.DataSourceSpecH5` just like silx does.
