### ISSUE TITLE
cannot create desktop using "larch -m" (Windows 10)

### ISSUE THREAD

**Issue by duoduoss** [xraypy/xraylarch#381]
Hello @newville 

After upgrading to the development version, I could not create the desktop folder using "larch -m".  I got the error message: 
Traceback (most recent call last):
  File "c:\programdata\xraylarch\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\xraylarch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\xraylarch\Scripts\larch.exe\__main__.py", line 4, in <module>
  File "c:\programdata\xraylarch\lib\site-packages\larch\apps.py", line 15, in <module>
    from .shell import shell
ImportError: cannot import name 'shell' from 'larch.shell' (c:\programdata\xraylarch\lib\site-packages\larch\shell.py)

Is there anyway to fix this? Thank you very much!

**Comment by newville** [comment]
@duoduoss I think this is now fixed and that re-installing the development wheel should now work.

**Comment by duoduoss** [comment]
@newville Yes, now it works! Thank you very much! 
However, I saw the path removing issues #377 showing up again. I found error message in Larch buffer:
Traceback (most recent calls last): 
    plot_chir(_feffit_dataset.model, label='model', win=1, rmax=8.0, show_window=False, new=False)
   File C:\Users\Dr. Yang Hu\larch\init.lar, line 2
  File "c:\programdata\xraylarch\lib\site-packages\larch\closure.py", line 76, in __call__
    return self.func(*args, **kwds)
  File "c:\programdata\xraylarch\lib\site-packages\larch\wxlib\xafsplots.py", line 522, in plot_chir
    _plot(dgroup.r, dgroup.chir_mag+offset, label='%s (mag)' % label, **opts)

AttributeError: 'Group' object has no attribute 'r'

Plus, now when I switch to EXAFS then back to Feff Fitting, the removed path shows up again and all path parameters set back to original states as they were just imported. No error message in buffer nor in terminal.
