### ISSUE TITLE
GSE Mapviewer (0.9.63) Fails to Open

### ISSUE THREAD

**Issue by mooaw** [xraypy/xraylarch#386]
Hi,

I updated Larch to 0.9.63, and GSE Mapviewer stops working. It doesn't open either by clicking the desktop icon or through the terminal. Other functionalities seem to be working fine. I've attached the error message below. I'm using Mac Monterey (12.4). Thanks for you help.

```
Traceback (most recent call last):
  File "/Users/mooaw/xraylarch/bin/gse_mapviewer", line 8, in <module>
    sys.exit(run_gse_mapviewer())
  File "/Users/mooaw/xraylarch/lib/python3.9/site-packages/larch/apps.py", line 146, in run_gse_mapviewer
    from larch.wxmap import MapViewer
  File "/Users/mooaw/xraylarch/lib/python3.9/site-packages/larch/wxmap/__init__.py", line 1, in <module>
    from ..wxlib import (gui_utils, ParameterPanel, PeriodicTablePanel,
ImportError: cannot import name 'XRFDisplayFrame' from 'larch.wxlib' (/Users/mooaw/xraylarch/lib/python3.9/site-packages/larch/wxlib/__init__.py)
```

**Comment by newville** [comment]
@mooaw oops thanks!  I just pushed 0.9.64 to fix this one bug.

**Comment by mooaw** [comment]
@newville works fine now. Thank you.
